# Generated by Django 4.0.4 on 2022-05-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='IngredientModel',
        ),
    ]
