# Generated by Django 4.0.4 on 2022-05-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_rename_category_categorymodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientmodel',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
