# Generated by Django 4.0.4 on 2022-05-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredientmodel_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
